### ISSUE TITLE
Feature Addition : Logging

### ISSUE THREAD

**Issue by Niketw** [opencodeiiita/YAKL#1]
# Feature Request: Logging Keystrokes  :trollface:

## **Description**  🧷
Add a logging feature to track and save user keystrokes in a log file. This functionality should be implemented in the `Logger` class (`logger.h` and `logger.cpp`).  

---

## **Acceptance Criteria**  🧷
1. A log file named `log.txt` should:  
   - Be located in the project root directory.  
   - Be automatically created if it does not exist.  
2. The `log.txt` file should contain the actual keys pressed (e.g., letters, numbers, special characters), **not key codes**.  
3. Implementation must use standard C++ file handling (`fstream`).  
4. Logged entries must:  
   - Be appended to the file (do not overwrite existing content).  
   - Be written in a readable format.  

---

## **Technical Details**  🧷
- **Class to Modify**: `Logger` (files: `logger.h` and `logger.cpp`).  
- Ensure compatibility with the project’s existing logging functionality (if any).  
- Avoid significant performance impacts due to file I/O operations.  

---

## **Additional Notes**  🧷
- Consider adding basic error handling for file operations (e.g., permissions, disk space).  
- If necessary, provide a simple mechanism to stop or pause logging (e.g., a boolean toggle in the `Logger` class).  

---

**Comment by Apoorv012** [comment]
claim

**Comment by Niketw** [comment]
Its tagged everyone, so no need to claim. Fix the issue and send PR's. Best solution (PR) will be merged.
