### ISSUE TITLE
Feature Addition : Stealth

### ISSUE THREAD

**Issue by Niketw** [opencodeiiita/YAKL#3]
# Feature Request: Stealth :trollface:

## **Description** 🧷
Add functionality to hide the terminal window and make the logger run as a background process.

---

## **Acceptance Criteria** 🧷
1. The terminal should not be visible.
2. The program should run as a background process.
3. Call the logger class in `main.cpp` and implement the logging feature.
4. The logger should be able to start automatically on system startup (as a service).

---

## **Additional Notes** 🧷
- Ensure that the logger runs silently in the background without affecting system performance.

---

**Comment by Navigam1108** [comment]
Claim
